version: '3.9'

services:
  smtp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI for MailHog
    restart: always
